print-progress: false
concurrent: 10
check-interval: 999999

media-check: false
speed-test-url: ""
enable-web-ui: false
disable-sub-store: true
memory-optimize: true

node-type:
  - vmess
  - ss
  - trojan

timeout: 8000
success-limit: 100
max-proxies-per-check: 500

save-method: gist
github-gist-id: ""
github-token: ""

listen-port: ""

sub-urls:
  - "PLACEHOLDER"
