print-progress: false
concurrent: 30
check-interval: 999999

media-check: false
speed-test-url: ""
enable-web-ui: false
disable-sub-store: true
memory-optimize: true
rename-node: true

node-type:
  - vmess
  - ss
  - trojan

timeout: 5000
success-limit: 200
max-proxies-per-check: 0

save-method: gist
github-gist-id: ""
github-token: ""

listen-port: ""

sub-urls:
  - "PLACEHOLDER"
